const game=document.getElementById('game'),startScreen=document.getElementById('startScreen'),gameOver=document.getElementById('gameOver'),start=document.getElementById('start'),restart=document.getElementById('restart'),shopScreen=document.getElementById('shopScreen'),shopButton=document.getElementById('shopButton'),closeShop=document.getElementById('closeShop'),shopGrid=document.getElementById('shopGrid'),shopCoins=document.getElementById('shopCoins');
let health=100,armor=0,ammo=12,kills=0,wave=1,coins=0,playing=false,reloading=false,shopOpen=false,gun=0,monsters=[],mouseX=innerWidth/2,mouseY=innerHeight/2,audioCtx=null;
const SAVE_KEY='killDaMonstersPlayer';
let profile={name:'Player',coins:0,totalKills:0,wins:0,owned:[true,...Array(15).fill(false)],lastPlayed:0};
try{const saved=JSON.parse(localStorage.getItem(SAVE_KEY)||'null');if(saved&&typeof saved==='object'){profile={...profile,...saved};if(!Array.isArray(profile.owned)||profile.owned.length!==16)profile.owned=[true,...Array(15).fill(false)];profile.owned[0]=true}}catch(e){}
function saveProfile(){try{profile.coins=coins;profile.totalKills=Math.max(profile.totalKills||0,kills);profile.owned=[...owned];profile.lastPlayed=Date.now();localStorage.setItem(SAVE_KEY,JSON.stringify(profile))}catch(e){}}
function sound(type){try{audioCtx=audioCtx||new(window.AudioContext||window.webkitAudioContext)();if(audioCtx.state==='suspended')audioCtx.resume();const o=audioCtx.createOscillator(),g=audioCtx.createGain(),t=audioCtx.currentTime;o.connect(g);g.connect(audioCtx.destination);if(type==='shoot'){o.type='sawtooth';o.frequency.setValueAtTime(150,t);o.frequency.exponentialRampToValueAtTime(55,t+.09);g.gain.setValueAtTime(.08,t);g.gain.exponentialRampToValueAtTime(.001,t+.1);o.start(t);o.stop(t+.1)}else{o.type='sine';o.frequency.setValueAtTime(300,t);o.frequency.exponentialRampToValueAtTime(500,t+.12);g.gain.setValueAtTime(.05,t);g.gain.exponentialRampToValueAtTime(.001,t+.13);o.start(t);o.stop(t+.13)}}catch(e){}}
const guns=[['RANGER PISTOL',12,1,0,'PISTOL','🔫'],['MONSTER SMG',30,1,100,'SMG','⚡'],['DOOM SHOTGUN',6,3,150,'SHOTGUN','💥'],['PHANTOM RIFLE',20,2,200,'RIFLE','🎯'],['THUNDER CANNON',4,6,300,'CANNON','⚡'],['VOID LASER',18,3,400,'LASER','🌀'],['SKULL MINIGUN',60,1,500,'MINIGUN','☠️'],['PLASMA BLASTER',10,8,650,'PLASMA','🔵'],['FROST SMG',36,2,750,'SMG','❄️'],['INFERNO SHOTGUN',8,5,850,'SHOTGUN','🔥'],['RAIL RIFLE',5,10,1000,'RAIL','🚄'],['GRAVITY LAUNCHER',3,12,1200,'LAUNCHER','🪐'],['ARC CANNON',12,7,1400,'CANNON','⚡'],['NOVA RIFLE',24,5,1600,'RIFLE','🌟'],['TITAN MINIGUN',80,2,2000,'MINIGUN','💀'],['SINGULARITY GUN',2,25,2500,'EXPERIMENTAL','🕳️']];
const gunKeys=['1','2','3','4','5','6','7','8','q','w','e','t','y','u','i','o'];let owned=profile.owned.slice();
function el(id){return document.getElementById(id)}function setText(id,v){const x=el(id);if(x)x.textContent=v}
function update(){setText('health',Math.max(0,health));setText('armor',armor);setText('ammo',ammo);setText('kills',kills);setText('wave',wave);setText('coins',coins);setText('weaponName',guns[gun][0]);setText('reserve',guns[gun][1]*5);setText('streakCount',kills);setText('shopCoins',coins);const hb=el('healthBar');if(hb)hb.style.width=Math.max(0,health)+'%';const ab=el('armorBar');if(ab)ab.style.width=armor+'%';saveProfile();if(!playing)return;if(monsters.length===0){wave++;spawnWave()}moveMonsters();setText('message',reloading?'RELOADING...':guns[gun][0])}
function begin(){sound('ui');health=100;armor=0;ammo=guns[gun][1];kills=0;wave=1;coins=profile.coins||0;reloading=false;shopOpen=false;owned=profile.owned.slice();owned[0]=true;monsters.forEach(m=>m.el.remove());monsters=[];playing=true;startScreen.classList.add('hidden');gameOver.classList.add('hidden');shopScreen.classList.add('hidden');spawnWave();update()}
function spawnWave(){for(let i=0;i<wave+2;i++)spawnMonster(i===wave+1&&wave%5===0)}function spawnMonster(boss){const e=document.createElement('div');e.className='monster'+(boss?' boss':'');e.innerHTML='<div class="head"><i class="eye a"></i><i class="eye b"></i></div><div class="body"></div><div class="arm a"></div><div class="arm b"></div>';const x=8+Math.random()*84,y=18+Math.random()*60;e.style.left=x+'vw';e.style.top=y+'vh';game.appendChild(e);monsters.push({el:e,x,y,hp:boss?18:2+Math.floor(wave/2),speed:boss?.008:.015+Math.random()*.025,boss})}
function moveMonsters(){monsters.forEach(m=>{const dx=50-m.x,dy=50-m.y,d=Math.hypot(dx,dy);if(d>8){m.x+=dx/d*m.speed;m.y+=dy/d*m.speed;m.el.style.left=m.x+'vw';m.el.style.top=m.y+'vh'}else if(Math.random()<.025){const dmg=m.boss?10:5;if(armor>0)armor=Math.max(0,armor-dmg);else health-=dmg;if(health<=0)endGame()}})}
function shoot(tx,ty){if(!playing||shopOpen||reloading||ammo<=0)return;sound('shoot');ammo--;const muzzle=document.createElement('div');muzzle.className='muzzle';muzzle.style.left=tx+'px';muzzle.style.top=ty+'px';game.appendChild(muzzle);setTimeout(()=>muzzle.remove(),90);const cx=innerWidth/2,cy=innerHeight/2,angle=Math.atan2(ty-cy,tx-cx);let target=null,best=Infinity;monsters.forEach(m=>{const x=m.x/100*innerWidth,y=m.y/100*innerHeight,a=Math.atan2(y-cy,x-cx),diff=Math.abs(Math.atan2(Math.sin(a-angle),Math.cos(a-angle))),d=Math.hypot(x-cx,y-cy);if(diff<.15&&d<best){best=d;target=m}});if(target){target.hp-=guns[gun][2];target.el.classList.add('hit');setTimeout(()=>target.el.classList.remove('hit'),100);if(target.hp<=0){target.el.remove();monsters=monsters.filter(m=>m!==target);kills++;coins+=target.boss?50:5;profile.totalKills=(profile.totalKills||0)+1}}if(ammo===0)reload();update()}
function reload(){if(!playing||shopOpen||reloading||ammo===guns[gun][1])return;reloading=true;setText('message','RELOADING...');setTimeout(()=>{ammo=guns[gun][1];reloading=false;update()},900)}
function buyArmor(){if(!playing||shopOpen||coins<50)return;coins-=50;armor=Math.min(100,armor+25);update()}
function openWeaponShop(){if(!playing)return;sound('ui');shopOpen=true;shopScreen.classList.remove('hidden');renderShop()}function closeWeaponShop(){sound('ui');shopOpen=false;shopScreen.classList.add('hidden');update()}
function renderShop(){if(!shopGrid)return;shopGrid.innerHTML='';setText('shopCoins',coins);guns.forEach((g,i)=>{const c=document.createElement('div');c.className='gun-card '+(owned[i]?'owned ':'locked ')+(gun===i?'selected':'');const action=gun===i?'EQUIPPED':owned[i]?'EQUIP':coins>=g[3]?'BUY NOW':'LOCKED';c.innerHTML='<div><div style="font-size:32px">'+g[5]+'</div><div class="gun-number">KEY: '+gunKeys[i].toUpperCase()+' · '+g[4]+'</div><div class="gun-name">'+g[0]+'</div><div class="gun-stats">MAG '+g[1]+' · POWER '+g[2]+'</div><div class="gun-price">'+(g[3]?'💰 '+g[3]+' COINS':'FREE')+'</div></div><button class="gun-action" '+(action==='LOCKED'?'disabled':'')+'>'+action+'</button>';c.onclick=()=>buyOrEquip(i);shopGrid.appendChild(c)})}
function buyOrEquip(i){if(owned[i]){gun=i;ammo=guns[i][1];setText('message','EQUIPPED: '+guns[i][0]);renderShop();update();return}if(coins>=guns[i][3]){coins-=guns[i][3];owned[i]=true;gun=i;ammo=guns[i][1];setText('message','PURCHASED: '+guns[i][0]);renderShop();update()}else setText('message','NOT ENOUGH COINS! NEED '+guns[i][3]+' COINS')}
function switchGun(i){if(!playing||shopOpen||reloading)return;if(owned[i]){gun=i;ammo=guns[i][1];sound('ui');update()}else openWeaponShop()}
function endGame(){playing=false;shopOpen=false;shopScreen.classList.add('hidden');profile.wins=profile.wins||0;saveProfile();setText('finalKills',kills);gameOver.classList.remove('hidden')}
function setupProfile(){let p=profile.name;if(!p||p==='Player'){const n=prompt('Enter your player name:','Player');if(n&&n.trim())profile.name=n.trim();saveProfile()}setText('playerName',profile.name)}
document.addEventListener('mousemove',e=>{mouseX=e.clientX;mouseY=e.clientY});document.addEventListener('keydown',e=>{const k=e.key.toLowerCase();if(k==='escape'&&shopOpen)closeWeaponShop();else if(k==='r')reload();else if(k==='b')buyArmor();else{const i=gunKeys.indexOf(k);if(i>=0)switchGun(i)}});game.addEventListener('mousedown',e=>{if(playing&&!shopOpen&&!e.target.closest('button'))shoot(e.clientX,e.clientY)});start.addEventListener('click',()=>{setupProfile();begin()});restart.addEventListener('click',begin);shopButton.addEventListener('click',openWeaponShop);closeShop.addEventListener('click',closeWeaponShop);setInterval(()=>{if(playing&&!shopOpen)update()},40);