const $=id=>document.getElementById(id),game=$('game'),startScreen=$('startScreen'),gameOver=$('gameOver'),start=$('start'),restart=$('restart'),shopScreen=$('shopScreen'),shopButton=$('shopButton'),closeShop=$('closeShop'),shopGrid=$('shopGrid');
let health=100,armor=0,ammo=12,kills=0,wave=1,coins=0,grenades=3,mines=2,playing=false,shopOpen=false,reloading=false,gun=0,sword=-1,monsters=[],mouseX=innerWidth/2,mouseY=innerHeight/2,playerX=50,playerY=65,keys={},audioCtx=null;
const SAVE='killDaMonstersPlayer';
const guns=[['RANGER PISTOL',12,8,0],['MONSTER SMG',30,10,100],['DOOM SHOTGUN',6,28,150],['PHANTOM RIFLE',20,16,200],['THUNDER CANNON',4,55,300],['VOID LASER',18,22,400],['SKULL MINIGUN',60,7,500],['PLASMA BLASTER',10,45,650],['FROST SMG',36,13,750],['INFERNO SHOTGUN',8,38,850],['RAIL RIFLE',5,80,1000],['GRAVITY LAUNCHER',3,95,1200],['ARC CANNON',12,65,1400],['NOVA RIFLE',24,48,1600],['TITAN MINIGUN',80,12,2000],['SINGULARITY GUN',2,130,2500],['VIPER PISTOL',15,15,2800],['RAPTOR SMG',40,13,3000],['MAMMOTH LMG',70,14,3300],['FALCON CARBINE',24,22,3600],['HAVOC SHOTGUN',10,45,3900],['RAVEN RIFLE',28,25,4200],['SCORPION MG',55,18,4500],['CYCLONE GUN',18,35,4800],['METEOR CANNON',8,70,5200],['FUSION RIFLE',32,55,5600],['GLACIER CANNON',14,80,6000],['SUNFIRE RIFLE',30,65,6400],['MOONLIGHT LASER',22,75,6800],['STORMBREAKER',20,100,7200],['NEBULA BLASTER',16,115,7600],['STARFORGE RIFLE',36,80,8200],['VOID HAMMER',9,180,8800],['PHOTON CANNON',12,150,9400],['QUANTUM SMG',50,45,10000],['DARK MATTER GUN',10,200,11000],['TITAN BUSTER',6,250,12000],['GHOST RIFLE',26,65,13000],['BOLT CASTER',18,110,14000],['CRYO RIFLE',28,80,15000],['LAVA LAUNCHER',7,220,16000],['PLAGUE BLASTER',34,55,17000],['COSMIC RIFLE',40,90,18500],['BLACKSTAR CANNON',5,300,20000],['DIMENSION RIFLE',20,200,22000],['DOOMBRINGER',8,280,24000],['INFINITY BLASTER',45,120,26000],['APEX MINIGUN',100,35,28000],['OMEGA CANNON',6,400,30000],['GODSLAYER',4,500,35000],['PHANTOM SMG',44,60,38000],['HELLSTORM RIFLE',25,150,42000],['EMP BLASTER',12,180,46000],['MAGNETAR CANNON',8,450,50000],['TIME RIFLE',20,300,55000],['PLANET CRUSHER',4,650,60000],['CHAOS REPEATER',80,65,70000],['DOOM RAY',3,900,80000]];
const swords=[['Training Sword',8,500],['Steel Saber',12,700],['Frost Blade',20,900],['Flame Katana',28,1100],['Thunder Sword',35,1400],['Shadow Blade',42,1800],['Void Katana',55,2300],['Plasma Sword',70,3000],['Dragon Blade',90,3800],['Galaxy Edge',120,5000],['Infinity Katana',160,7000],['Omega Blade',220,10000],['Godslayer Sword',300,15000]];
const keymap=['1','2','3','4','5','6','7','8','q','w','e','t','y','u','i','o'];
let profile={name:'Player',coins:0,totalKills:0,grenades:3,mines:2,owned:[true],swords:[]};try{profile={...profile,...JSON.parse(localStorage.getItem(SAVE)||'{}')}}catch(e){}let owned=Array.from({length:guns.length},(_,i)=>i===0||profile.owned?.[i]===true),ownedSwords=Array.isArray(profile.swords)?profile.swords:[];coins=Number(profile.coins)||0;
function save(){try{profile.coins=coins;profile.grenades=grenades;profile.mines=mines;profile.owned=[...owned];profile.swords=[...ownedSwords];profile.lastPlayed=Date.now();localStorage.setItem(SAVE,JSON.stringify(profile))}catch(e){}}
function sound(type){try{audioCtx=audioCtx||new(window.AudioContext||window.webkitAudioContext)();if(audioCtx.state==='suspended')audioCtx.resume();const o=audioCtx.createOscillator(),g=audioCtx.createGain(),t=audioCtx.currentTime;o.connect(g);g.connect(audioCtx.destination);o.type=type==='shoot'?'sawtooth':'sine';o.frequency.setValueAtTime(type==='shoot'?150:type==='buy'?650:360,t);o.frequency.exponentialRampToValueAtTime(type==='shoot'?55:850,t+.08);g.gain.setValueAtTime(.05,t);g.gain.exponentialRampToValueAtTime(.001,t+.1);o.start(t);o.stop(t+.1)}catch(e){}}
function ui(){if($('health'))$('health').textContent=Math.max(0,health);if($('armor'))$('armor').textContent=armor;if($('ammo'))$('ammo').textContent=ammo;if($('kills'))$('kills').textContent=kills;if($('wave'))$('wave').textContent=wave;if($('coins'))$('coins').textContent=coins;if($('weaponName'))$('weaponName').textContent=sword>=0?swords[sword][0]:guns[gun][0];if($('reserve'))$('reserve').textContent=guns[gun][1]*5;if($('healthBar'))$('healthBar').style.width=Math.max(0,health)+'%';if($('armorBar'))$('armorBar').style.width=armor+'%';if($('shopCoins'))$('shopCoins').textContent=coins;if($('message'))$('message').textContent=reloading?'RELOADING...':(sword>=0?swords[sword][0]:guns[gun][0])+'  |  💣 '+grenades+'  |  🪤 '+mines;save()}
function spawnMob(boss=false){const e=document.createElement('div');e.className='monster'+(boss?' boss':'');e.innerHTML='<div class="head"><i class="eye a"></i><i class="eye b"></i></div><div class="body"></div><div class="arm a"></div><div class="arm b"></div>';const x=8+Math.random()*84,y=18+Math.random()*60;e.style.left=x+'vw';e.style.top=y+'vh';game.appendChild(e);monsters.push({el:e,x,y,hp:boss?18:2+Math.floor(wave/2),boss})}
function waveUp(){for(let i=0;i<wave+2;i++)spawnMob(i===wave+1&&wave%5===0)}
function movePlayer(){const s=.6;if(keys.w)playerY=Math.max(35,playerY-s);if(keys.s)playerY=Math.min(88,playerY+s);if(keys.a)playerX=Math.max(5,playerX-s);if(keys.d)playerX=Math.min(95,playerX+s)}
function moveMonsters(){monsters.forEach(m=>{const dx=playerX-m.x,dy=playerY-m.y,d=Math.hypot(dx,dy)||1;if(d>7){const s=m.boss?.008:.015;m.x+=dx/d*s;m.y+=dy/d*s;m.el.style.left=m.x+'vw';m.el.style.top=m.y+'vh'}else if(Math.random()<.025){const d=m.boss?10:5;if(armor)armor=Math.max(0,armor-d);else health-=d;if(health<=0)end()}})}
function begin(){health=100;armor=0;ammo=guns[0][1];gun=0;sword=-1;kills=0;wave=1;grenades=Math.max(0,Number(profile.grenades??3));mines=Math.max(0,Number(profile.mines??2));coins=Number(profile.coins)||0;owned=Array.from({length:guns.length},(_,i)=>i===0||profile.owned?.[i]===true);ownedSwords=Array.isArray(profile.swords)?profile.swords:[];playing=true;startScreen.classList.add('hidden');gameOver.classList.add('hidden');shopScreen.classList.add('hidden');monsters.forEach(m=>m.el.remove());monsters=[];playerX=50;playerY=65;waveUp();ui()}
function target(tx,ty){const cx=innerWidth*(playerX/100),cy=innerHeight*(playerY/100),ang=Math.atan2(ty-cy,tx-cx);let t=null,b=Infinity;monsters.forEach(m=>{const x=m.x/100*innerWidth,y=m.y/100*innerHeight,a=Math.atan2(y-cy,x-cx),dif=Math.abs(Math.atan2(Math.sin(a-ang),Math.cos(a-ang))),d=Math.hypot(x-cx,y-cy);if(dif<.15&&d<b){b=d;t=m}});return t}
function defeat(m){m.el.remove();monsters=monsters.filter(z=>z!==m);kills++;profile.totalKills=(profile.totalKills||0)+1;coins+=m.boss?50:5}
function shoot(tx,ty){if(!playing||shopOpen||reloading||ammo<=0||sword>=0)return;sound('shoot');ammo--;const t=target(tx,ty);if(t){t.hp-=guns[gun][2];if(t.hp<=0)defeat(t)}if(ammo===0)reload();ui()}
function slash(){if(!playing||shopOpen||sword<0)return;const cx=playerX,cy=playerY;monsters.slice().forEach(m=>{if(Math.hypot(m.x-cx,m.y-cy)<13){m.hp-=swords[sword][1];if(m.hp<=0)defeat(m)}});ui()}
function grenade(tx,ty){if(!playing||shopOpen||grenades<=0)return;grenades--;sound('grenade');setTimeout(()=>{monsters.slice().forEach(m=>{if(Math.hypot(m.x/100*innerWidth-tx,m.y/100*innerHeight-ty)<150){m.hp-=20;if(m.hp<=0)defeat(m)}});ui()},500);ui()}
function mine(tx,ty){if(!playing||shopOpen||mines<=0)return;mines--;sound('mine');const n=document.createElement('div');n.style.cssText=`position:absolute;left:${tx}px;top:${ty}px;width:24px;height:24px;border-radius:50%;background:#111;border:3px solid #d44;z-index:40`;game.appendChild(n);const timer=setInterval(()=>{if(!n.isConnected){clearInterval(timer);return}for(const m of monsters){if(Math.hypot(m.x/100*innerWidth-tx,m.y/100*innerHeight-ty)<70){clearInterval(timer);n.remove();monsters.slice().forEach(z=>{if(Math.hypot(z.x/100*innerWidth-tx,z.y/100*innerHeight-ty)<120){z.hp-=20;if(z.hp<=0)defeat(z)}});ui();break}}},100);setTimeout(()=>{clearInterval(timer);n.remove()},30000);ui()}
function reload(){if(!playing||shopOpen||reloading||sword>=0||ammo===guns[gun][1])return;reloading=true;sound('reload');setTimeout(()=>{ammo=guns[gun][1];reloading=false;ui()},700)}
function buyGun(i){if(owned[i]){sword=-1;gun=i;ammo=guns[i][1];sound('buy');render();ui();return}if(coins<guns[i][3])return;if(coins>=guns[i][3]){coins-=guns[i][3];owned[i]=true;sword=-1;gun=i;ammo=guns[i][1];sound('buy');render();ui()}}
function buySword(i){if(ownedSwords.includes(i)){sword=i;sound('buy');render();ui();return}if(coins<swords[i][2])return;coins-=swords[i][2];ownedSwords.push(i);sword=i;sound('buy');render();ui()}
function render(){if(!shopGrid)return;shopGrid.innerHTML='';guns.forEach((g,i)=>{const c=document.createElement('div'),state=owned[i]?(sword<0&&gun===i?'EQUIPPED':'EQUIP'):(coins>=g[3]?'BUY NOW':'LOCKED');c.className='gun-card '+(owned[i]?'owned ':'locked ')+(state==='EQUIPPED'?'selected':'');c.innerHTML=`<div><div style="font-size:28px">🔫</div><div class="gun-name">${g[0]}</div><div class="gun-stats">MAG ${g[1]} · POWER ${g[2]}</div><div class="gun-price">💰 ${g[3]}</div></div><button class="gun-action">${state}</button>`;c.onclick=()=>buyGun(i);shopGrid.appendChild(c)});swords.forEach((s,i)=>{const c=document.createElement('div'),own=ownedSwords.includes(i),state=own?(sword===i?'EQUIPPED':'EQUIP'):(coins>=s[2]?'BUY NOW':'LOCKED');c.className='gun-card '+(own?'owned ':'locked ')+(state==='EQUIPPED'?'selected':'');c.innerHTML=`<div><div style="font-size:28px">⚔️</div><div class="gun-name">${s[0]}</div><div class="gun-stats">DAMAGE ${s[1]} · MELEE</div><div class="gun-price">💰 ${s[2]}</div></div><button class="gun-action">${state}</button>`;c.onclick=()=>buySword(i);shopGrid.appendChild(c)})}
function openShop(){if(!playing)return;shopOpen=true;shopScreen.classList.remove('hidden');render()}function closeShopNow(){shopOpen=false;shopScreen.classList.add('hidden');ui()}function end(){playing=false;shopOpen=false;shopScreen.classList.add('hidden');if($('finalKills'))$('finalKills').textContent=kills;save();gameOver.classList.remove('hidden')}
start.onclick=begin;restart.onclick=begin;shopButton.onclick=openShop;closeShop.onclick=closeShopNow;document.addEventListener('mousemove',e=>{mouseX=e.clientX;mouseY=e.clientY});document.addEventListener('keydown',e=>{const k=e.key.toLowerCase();keys[k]=true;if(k==='r')reload();else if(k==='g')grenade(mouseX,mouseY);else if(k==='m')mine(mouseX,mouseY);else if(k==='v')slash();else if(k==='escape'&&shopOpen)closeShopNow();else{const i=keymap.indexOf(k);if(i>=0&&playing&&!shopOpen&&owned[i]){sword=-1;gun=i;ammo=guns[i][1];ui()}}});document.addEventListener('keyup',e=>{keys[e.key.toLowerCase()]=false});game.addEventListener('mousedown',e=>{if(!playing||shopOpen||e.target.closest('button'))return;if(e.button===2){e.preventDefault();grenade(e.clientX,e.clientY)}else if(e.button===0){if(e.shiftKey)slash();else shoot(e.clientX,e.clientY)}});game.addEventListener('contextmenu',e=>{if(playing)e.preventDefault()});setInterval(()=>{if(playing&&!shopOpen){movePlayer();if(monsters.length===0){wave++;waveUp()}moveMonsters();ui()}},40);