(()=>{
'use strict';
const game=document.getElementById('game');
if(!game)return;
const spiders=[];let lastWave=0,lastSpawn=0;
const style=document.createElement('style');
style.textContent='.rad-spider{position:absolute;width:44px;height:34px;z-index:65;pointer-events:auto;filter:drop-shadow(0 0 10px #7cff00);cursor:crosshair}.rad-spider .core{position:absolute;left:12px;top:7px;width:20px;height:20px;border-radius:50%;background:radial-gradient(circle,#e8ff9a 0 18%,#7cff00 40%,#163b08 75%);border:2px solid #bfff66;box-shadow:0 0 18px #7cff00}.rad-spider i{position:absolute;width:18px;height:4px;background:#70a84a;border-radius:5px;box-shadow:0 0 6px #7cff00}.rad-spider i:nth-child(2){left:0;top:5px;transform:rotate(-24deg)}.rad-spider i:nth-child(3){left:0;top:14px;transform:rotate(-10deg)}.rad-spider i:nth-child(4){left:0;top:23px;transform:rotate(18deg)}.rad-spider i:nth-child(5){right:0;top:5px;transform:rotate(204deg)}.rad-spider i:nth-child(6){right:0;top:14px;transform:rotate(190deg)}.rad-spider i:nth-child(7){right:0;top:23px;transform:rotate(162deg)}.rad-spider .label{position:absolute;top:-18px;left:50%;transform:translateX(-50%);font:900 8px Arial;letter-spacing:1px;color:#bfff66;text-shadow:0 1px 4px #000;white-space:nowrap}.rad-hit{animation:radPop .18s ease-out}.rad-burst{position:absolute;width:90px;height:90px;border:3px solid #aaff55;border-radius:50%;transform:translate(-50%,-50%);pointer-events:none;z-index:64;animation:radBurst .3s ease-out forwards}@keyframes radPop{50%{transform:scale(1.25)}}@keyframes radBurst{to{opacity:0;transform:translate(-50%,-50%) scale(1.8)}}';
document.head.appendChild(style);
function active(){return !!window.KDM&&window.KDM.isPlaying()&&!window.KDM.isShopOpen()}
function spawn(){if(!active()||spiders.length>=5)return;const s=document.createElement('div');s.className='rad-spider';s.innerHTML='<span class="core"></span><i></i><i></i><i></i><i></i><i></i><i></i><span class="label">☢ RADIOACTIVE</span>';const p=window.KDM.getPlayer();let x=8+Math.random()*84,y=18+Math.random()*62;if(Math.hypot(x-p.x,y-p.y)<18)x=x<50?72:18;s.style.left=x+'vw';s.style.top=y+'vh';game.appendChild(s);const obj={el:s,x,y,hp:3,speed:.022+Math.random()*.016,attackAt:0};spiders.push(obj);s.addEventListener('mousedown',e=>{e.stopPropagation();damage(obj,3,e.clientX,e.clientY)})}
function damage(s,dmg=1,tx=null,ty=null){if(!s.el.isConnected)return;s.hp-=dmg;s.el.classList.add('rad-hit');setTimeout(()=>s.el.classList.remove('rad-hit'),100);if(s.hp<=0){const r=s.el.getBoundingClientRect(),x=tx??r.left+r.width/2,y=ty??r.top+r.height/2,b=document.createElement('div');b.className='rad-burst';b.style.left=x+'px';b.style.top=y+'px';game.appendChild(b);setTimeout(()=>b.remove(),320);s.el.remove();const i=spiders.indexOf(s);if(i>=0)spiders.splice(i,1);if(window.KDM)window.KDM.addKill();}}
function tick(){if(!active()){spiders.splice(0).forEach(s=>s.el.remove());return}const wave=Number(document.getElementById('wave')?.textContent||1);if(wave!==lastWave){lastWave=wave;const count=Math.min(3,1+Math.floor(wave/3));for(let i=0;i<count;i++)setTimeout(spawn,i*250)}if(Date.now()-lastSpawn>10000){lastSpawn=Date.now();if(Math.random()<.75)spawn()}const p=window.KDM.getPlayer();for(const s of spiders.slice()){const dx=p.x-s.x,dy=p.y-s.y,d=Math.hypot(dx,dy)||1;if(d>8){s.x+=dx/d*s.speed;s.y+=dy/d*s.speed;s.el.style.left=s.x+'vw';s.el.style.top=s.y+'vh'}else if(performance.now()>s.attackAt){window.KDM.damagePlayer(4);s.attackAt=performance.now()+1200;s.el.classList.add('rad-hit');setTimeout(()=>s.el.classList.remove('rad-hit'),120)}}}
setInterval(tick,50);
})();